version: "3"

services:
  haproxy:
    image: dockercloud/haproxy
    networks:
      - swarm_api_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    ports:
      - 80:80

networks:
  swarm_api_network:
    external: true